Source = Excel.Workbook(File.Contents("C:\Users\Allsaint\Downloads\AZUKA\CASE STUDIES\LAPTOP REVIEW\laptop review.xlsx"), null, true),
#"Form responses 1_Sheet" = Source{[Item="Form responses 1",Kind="Sheet"]}[Data],
#"Promoted Headers" = Table.PromoteHeaders(#"Form responses 1_Sheet", [PromoteAllScalars=true]),
#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Timestamp", type datetime}, {"Email address", type text}, {"What country do you reside in currently? ", type any}, {"What State  you currently reside in?", type text}, {"What gender do you Identify as?  ", type text}, {"  What Age bracket do you fall under?  ", type text}, {"  What is your Current profession?  ", type text}, {"Which of the following brands would you prefer if you were to purchase this product category today? (Select only one.)  ", type text}, {"Which is your least laptop brand to consider purchasing", type text}, {"What Battery life span are you satisfied with?  ", type text}, {"what is your preferred laptop size?  ", type text}, {"How much RAM are you satisfied with?", type text}, {"What storage capacity or ROM do you look out for?", type text}, {"Are graphics card important to you?", type text}, {"If yes to the previous question, which would you consider?", type text}, {"What is your preferred CPU type ?", type text}, {"How many USB ports do you mind having?", type text}, {"Do you mind if your laptop is a touch screen Display?", type text}, {"Do you mind if your Laptop is convertible (it rotates or it is detachable)", type text}, {"Are loud inbuilt Speakers important to you?", type text}, {"What additional Computer Accessories do you use with your laptop?", type text}, {"Do you have a preferred choice of color?", type text}, {"Do you mind having keyboard lights?", type text}, {"What is your budget?", type text}, {"What is your most important feature when looking to get a new laptop?  ", type text}, {"Are there additional specifications you look out for when purchasing your laptop?", type text}}),
#"Replaced Value1" = Table.ReplaceValue(#"Changed Type",null,"none",Replacer.ReplaceValue,{"Are there additional specifications you look out for when purchasing your laptop?"}),
#"Filtered Rows1" = Table.SelectRows(#"Replaced Value1", each true),
#"Replaced Value" = Table.ReplaceValue(#"Filtered Rows1","Nil","none",Replacer.ReplaceText,{"Are there additional specifications you look out for when purchasing your laptop?"}),
#"Replaced Value2" = Table.ReplaceValue(#"Replaced Value","1","Nigeria",Replacer.ReplaceText,{"Are there additional specifications you look out for when purchasing your laptop?"}),
#"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",1,"Nigeria",Replacer.ReplaceValue,{"What country do you reside in currently? "}),
#"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",2,"Nigeria",Replacer.ReplaceValue,{"What country do you reside in currently? "}),
#"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4",234,"Nigeria",Replacer.ReplaceValue,{"What country do you reside in currently? "}),
#"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","NIGERIA","Nigeria",Replacer.ReplaceText,{"What country do you reside in currently? "}),
#"Filtered Rows" = Table.SelectRows(#"Replaced Value6", each true)
in
#"Filtered Rows"
